export const GET_ITEMS = "GET_ITEMS"; // TESTING PURPOSES
export const ADD_ITEM = "ADD_ITEM"; // TESTING PURPOSES
export const DELETE_ITEM = "DELETE_ITEM"; // TESTING PURPOSES
export const ITEMS_LOADING = "ITEMS_LOADING"; // TESTING PURPOSES

export const GET_EMPLOYEES = "GET_EMPLOYEES"; // TESTING PURPOSES
export const ADD_EMPLOYEE = "ADD_EMPLOYEE"; // TESTING PURPOSES
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"; // TESTING PURPOSES
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE"; // TESTING PURPOSES
export const EMPLOYEES_LOADING = "EMPLOYEES_LOADING"; // TESTING PURPOSES

export const GET_EMPLOYEE_TESTS = "GET_EMPLOYEE_TESTS"; // TESTING PURPOSES
export const ADD_EMPLOYEE_TEST = "ADD_EMPLOYEE_TEST"; // TESTING PURPOSES
export const DELETE_EMPLOYEE_TEST = "DELETE_EMPLOYEE_TEST"; // TESTING PURPOSES
export const UPDATE_EMPLOYEE_TEST = "UPDATE_EMPLOYEE_TEST"; // TESTING PURPOSES
export const EMPLOYEE_TESTS_LOADING = "EMPLOYEE_TESTS_LOADING"; // TESTING PURPOSES
