export const GET_ITEMS = "GET_ITEMS"; // TESTING PURPOSES
export const ADD_ITEM = "ADD_ITEM"; // TESTING PURPOSES
export const DELETE_ITEM = "DELETE_ITEM"; // TESTING PURPOSES
export const ITEMS_LOADING = "ITEMS_LOADING"; // TESTING PURPOSES

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const EMPLOYEES_LOADING = "EMPLOYEES_LOADING";

export const GET_EMPLOYEE_TESTS = "GET_EMPLOYEE_TESTS";
export const ADD_EMPLOYEE_TEST = "ADD_EMPLOYEE_TEST";
export const DELETE_EMPLOYEE_TEST = "DELETE_EMPLOYEE_TEST";
export const UPDATE_EMPLOYEE_TEST = "UPDATE_EMPLOYEE_TEST";
export const EMPLOYEE_TESTS_LOADING = "EMPLOYEE_TESTS_LOADING";

export const GET_POOL_MAPS = "GET_POOL_MAPS";
export const ADD_POOL_MAP = "ADD_POOL_MAP";
export const DELETE_POOL_MAP = "DELETE_POOL_MAP";
export const UPDATE_POOL_MAP = "UPDATE_POOL_MAP";
export const POOL_MAPS_LOADING = "POOL_MAPS_LOADING";

export const GET_POOLS = "GET_POOLS";
export const ADD_POOL = "ADD_POOL";
export const DELETE_POOL = "DELETE_POOL";
export const UPDATE_POOL = "UPDATE_POOL";
export const POOLS_LOADING = "POOLS_LOADING";

export const GET_WELL_TESTINGS = "GET_WELL_TESTINGS";
export const ADD_WELL_TESTING = "ADD_WELL_TESTING";
export const DELETE_WELL_TESTING = "DELETE_WELL_TESTING";
export const UPDATE_WELL_TESTING = "UPDATE_WELL_TESTING";
export const WELL_TESTINGS_LOADING = "WELL_TESTINGS_LOADING";
