export const GET_ITEMS = "GET_ITEMS"; // TESTING PURPOSES
export const ADD_ITEM = "ADD_ITEM"; // TESTING PURPOSES
export const DELETE_ITEM = "DELETE_ITEM"; // TESTING PURPOSES

export const GET_EMPLOYEES = "GET_EMPLOYEES"; // TESTING PURPOSES
export const ADD_EMPLOYEE = "ADD_EMPLOYEE"; // TESTING PURPOSES
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"; // TESTING PURPOSES
